---
driver:
  name: vagrant

transport:
  name: sftp
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  roles_path: catalog/
  requirements_path: requirements.yml
  hosts: all
  playbook: test/test.yml
  ansible_cfg_path: ansible.cfg
  ansible_vault_password_file: ~/ansible-secret.txt
  ansible_verbose: true
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_version: latest
  require_ansible_omnibus: false
  ansible_connection: ssh
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  # Ubuntu Trusty Tahr
  - name: U14.04.5-CKAN2.3
    driver: 
      box: dhoppe/ubuntu-14.04.5-amd64-nocm
      box_check_update: true
      customize:
        memory: 4096
      provision: true
      network:
        - ["private_network", {ip: "192.168.10.82"}]
      vm_hostname: catalog.local
  - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
